{
 "title": "Inverter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Grid voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Grid voltage",
     "measurement": "grid_voltage",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "Grid frequency",
     "measurement": "grid_frequency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC output voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "AC output voltage",
     "measurement": "ac_output_voltage",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC output frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "AC output frequency",
     "measurement": "ac_output_frequency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC output apparent power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "voltamp" }
   ],
   "targets": [
    {
     "alias": "AC output apparent power",
     "measurement": "ac_output_apparent_power",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC output active power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "AC output active power",
     "measurement": "ac_output_active_power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output load percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Output load percent",
     "measurement": "output_load_percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "BUS voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "BUS voltage",
     "measurement": "bus_voltage",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "measurement": "battery_voltage",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery charging current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "Battery charging current",
     "measurement": "battery_charging_current",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Battery capacity",
     "measurement": "battery_capacity",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter heat sink temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Inverter heat sink temperature",
     "measurement": "inverter_heat_sink_temperature",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Input current for battery",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "PV Input current for battery",
     "measurement": "pv_input_current_for_battery",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Input voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "PV Input voltage",
     "measurement": "pv_input_voltage",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery voltage from SCC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage from SCC",
     "measurement": "battery_voltage_from_scc",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery discharge current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "Battery discharge current",
     "measurement": "battery_discharge_current",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery voltage offset for fans on",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "mvolt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage offset for fans on",
     "measurement": "battery_voltage_offset_for_fans_on",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Charging power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "PV Charging power",
     "measurement": "pv_charging_power",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Device status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Is SBU priority version added",
     "measurement": "is_sbu_priority_version_added",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Is configuration changed",
     "measurement": "is_configuration_changed",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Is SCC firmware updated",
     "measurement": "is_scc_firmware_updated",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Is load on",
     "measurement": "is_load_on",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Is battery voltage to steady while charging",
     "measurement": "is_battery_voltage_to_steady_while_charging",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Is charging on",
     "measurement": "is_charging_on",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Is SCC charging on",
     "measurement": "is_scc_charging_on",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Is AC charging on",
     "measurement": "is_ac_charging_on",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Is charing to floating enabled",
     "measurement": "is_charging_to_floating_enabled",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Is switch on",
     "measurement": "is_switch_on",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Is dustproof installed",
     "measurement": "is_dustproof_installed",
     "query": "SELECT \"value\" FROM \"autogen\".\"battery_capacity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}