---
version: 1
disable_existing_loggers: False
formatters:
    brief:
        format: "%(message)s"
    precise:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: precise

root:
      level: INFO
      handlers: [console]
